name: check and publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: astro/package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: astro

      - name: Build
        run: npm run build
        working-directory: astro

      - name: Publish
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'astro/dist'
          destination-github-username: 'lpantano'
          destination-repository-name: 'lpantano.github.io'
          user-email: lorena.pantano@gmail.com
